Archive 'ngx-discovery'
vidal-community/ngx-discovery pull request #2
Opened 2018-09-24 15:20 UTC by fhiegel

2018-09-24 15:26 UTC, s-petit approved these changes

2018-09-25 06:17 UTC, nicokosi commented on README.md
> +This repo has been deprecated in favor of [ngx-discovery](https://github.com/vidal-community/ngx-discovery).
Seems recursive. :wink: [vidal-community/ng2-discovery](https://github.com/vidal-community/ng2-discovery), maybe? :eyeglasses:

2018-09-25 06:32 UTC, nicokosi requested changes

2018-09-25 06:32 UTC, nicokosi commented on README.md
> +> Archived
Instead of this "archived" label with blockquotes, what about being more explicit, like:

**This project is not maintained anymore.** It has been deprecated in favor of [vidal-community/ng2-discovery](https://github.com/vidal-community/ng2-discovery).

2018-09-25 08:09 UTC, nicokosi approved these changes
:+1:

2018-09-25 08:10 UTC, merged